### ISSUE TITLE
`libunistring` is a nice wrapper of `libiconv`

### ISSUE THREAD

**Issue by iahung2** [soasis/cuneicode#10]
https://thephd.dev/the-c-c++-rust-string-text-encoding-api-landscape

In your article, you didn't mention it.

**Comment by ThePhD** [comment]
Notes for myself:

libunistring is here -- https://github.com/gnosis/libunistring
its the usual FOSS stuff, might be worth reading and looking over when re-engaging with the cuneicode work again.

**Comment by iahung2** [comment]
> Notes for myself:
> 
> libunistring is here -- https://github.com/gnosis/libunistring its the usual FOSS stuff, might be worth reading and looking over when re-engaging with the cuneicode work again.

This mirror on Github is dead. `libunistring` is stilla actively developed: https://git.savannah.gnu.org/gitweb/?p=libunistring.git

**Comment by ThePhD** [comment]
Thanks for pointing that out! I'll make sure to use the savannah when I check it over.
