### ISSUE TITLE
Build fails with GCC 12.2.1 and Clang 14.0.5

### ISSUE THREAD

**Issue by bkmgit** [soasis/cuneicode#3]
When building commit 2f30d70 on Fedora linux, get the following error:

/home/cuneicode/source/ztd/cuneicode/detail/index.cpp:74:33: error: no member named 'ranges_adl' in namespace 'ztd::ranges'
                        auto __last = ::ztd::ranges::ranges_adl::adl_cend(__index_code_point_map);
                                      ~~~~~~~~~~~~~~~^

**Comment by ThePhD** [comment]
Yeah, sorry about that; super recent change to ztd.idk dependency. Should no longer trigger (as well as a bunch of other changes just pushed); thanks for reporting!

Fixed in https://github.com/soasis/cuneicode/commit/e6c16fa7e6bc20d97d58165c312f6c8a4f2e9670.

**Comment by bkmgit** [comment]
Thanks for your quick response. It builds with Clang. With GCC if warnings are treated as errors, the flag `-Wmaybe-uninitialized` prevents building. Thus one may want to add the options `-DCMAKE_C_FLAGS=-Wno-maybe-uninitialized -DCMAKE_CXX_FLAGS=-Wno-maybe-uninitialized`. The first time `-Wmaybe-uninitialized` raises an error is when compiling simdutf, but his error does not appear when compiling simdutf on its own.  This flag has been known to raise spurious issues.
