### ISSUE TITLE
`libiconv` output size counting

### ISSUE THREAD

**Issue by iahung2** [soasis/cuneicode#9]
https://thephd.dev/cuneicode-and-the-future-of-text-in-c

> output size counting `(iconv(cd, inbuf, inbytesleft, nullptr, outbytesleft));`

I'm not very sure about this. `libiconv` has the concept of reversible and irreversible mappings. From the manual of it, it said it will only `returns the number of non-reversible conversions performed during this call.`

https://www.gnu.org/savannah-checkouts/gnu/libiconv/documentation/libiconv-1.17/iconv.3.html

I have no idea if this number is the same as the output size or not.

Btw, I have never seen people on the internet use `libiconv` this way. Most of the time, they guess the output size. I don't even know that it's possible to have `iconv` to do a dry run to calculate the output size like this. I think this is `libicu` style!

https://stackoverflow.com/questions/13297458/simple-utf8-utf16-string-conversion-with-iconv

**Comment by ThePhD** [comment]
For posterity; the reason the article shows that is to show what iconv **doesn't** do, not what it does do. This was an example of things the API iconv could do but never actually goes as far as completing. From the article:

> … while the libiconv library itself **will fail to utilize the interface for the purposes we will list just below**, we ourselves can adapt it to do these kinds of operations …

(emphasis mine)
